---
- name: Create CIFS Server on NetApp using REST API
  hosts: localhost
  connection: local
  gather_facts: no
  vars_files:
    - vars.yml
    - collected_source_cifs_server_info.yml

  tasks:
    - name: Read CIFS Server details from cifs_server_dr.yml
      include_vars:
        file: collected_source_cifs_server_info.yml
        name: source_cifs_server_details

    - name: Debug loaded CIFS Server details
      debug:
        var: source_cifs_server_details

    - name: Get UUID of source Vserver
      uri:
        url: "https://{{ source_host }}/api/svm/svms?name={{ source_vserver }}"
        method: GET
        headers:
          Authorization: "{{ auth_header }}"
          Content-Type: "application/json"
        validate_certs: no
      register: source_vserver_info

    - name: Set source_vserver UUID
      set_fact:
        source_vserver_uuid: "{{ source_vserver_info.json.records[0].uuid }}"

    - name: Create CIFS Server
      uri:
        url: "https://{{ source_host }}/api/protocols/cifs/services/{{ source_vserver_info.json.records[0].uuid }}"
        method: POST
        body_format: json
        headers:
          Authorization: "{{ auth_header }}"
          Content-Type: "application/json"
        body:
          name: "{{ source_cifs_server_details.name }}"
          ad_domain.fqdn: "{{ source_cifs_server_details.ad_domain.fqdn }}"
          ad_domain.organizational_unit: "{{ source_cifs_server_details.ad_domain.organizational_unit }}"
          ad_domain.user: "{{ ad_domain_user }}"
          ad_domain.password: "{{ ad_domain_password }}"
          comment: "{{ source_cifs_server_details.comment }}"
        force: true
        validate_certs: no
        status_code: 201
