---
- name: Manage source vserver operations
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - vars.yml

  tasks:
    - name: Get the UUID of the source vserver
      uri:
        url: "https://{{ source_host }}/api/svm/svms?name={{ source_vserver }}"
        method: GET
        headers:
          Authorization: "{{ auth_header }}"
          Content-Type: "application/json"
        validate_certs: false
      register: svm_info

    - name: Debug SVM info
      debug:
        var: svm_info

    - name: Set SVM UUID fact
      set_fact:
        source_svm_uuid: "{{ svm_info.json.records[0].uuid }}"
        
    - name: Stop CIFS server on source_vserver
      uri:
        url: "https://{{ source_host }}/api/protocols/cifs/services/{{ source_svm_uuid }}"
        method: PATCH
        headers:
          Authorization: "{{ auth_header }}"
          Content-Type: "application/json"
        body:
          enabled: false
        body_format: json
        validate_certs: false
      register: stop_cifs_response
      ignore_errors: true

    - name: Debug stop CIFS server response
      debug:
        var: stop_cifs_response

    - name: Get list of volumes in source_vserver
      uri:
        url: "https://{{ source_host }}/api/storage/volumes?svm.name={{ source_vserver }}"
        method: GET
        headers:
          Authorization: "{{ auth_header }}"
          Content-Type: "application/json"
        validate_certs: false
      register: volumes_response

    - name: Debug volumes response
      debug:
        var: volumes_response

    - name: Create snapshot on each volume in source_vserver that doesn't contain 'root' or 'vsrv'
      uri:
        url: "https://{{ source_host }}/api/storage/volumes/{{ item.uuid }}/snapshots"
        method: POST
        headers:
          Authorization: "{{ auth_header }}"
          Content-Type: "application/json"
        body:
          name: "DR_TEST"
        body_format: json
        validate_certs: false
      with_items: "{{ volumes_response.json.records }}"
      when: 
        - "item.name is defined"
        - "'root' not in item.name"
        - "'vsrv' not in item.name"
      loop_control:
        loop_var: item
      register: snapshot_responses
      ignore_errors: true

    - name: Debug snapshot responses
      debug:
        var: snapshot_responses

    - name: Stop source_vserver
      uri:
        url: "https://{{ source_host }}/api/svm/svms/{{ source_svm_uuid }}"
        method: PATCH
        headers:
          Authorization: "{{ auth_header }}"
          Content-Type: "application/json"
        body:
          state: "stopped"
        body_format: json
        validate_certs: false
      register: stop_vserver_response
      ignore_errors: true

    - name: Debug stop vserver response
      debug:
        var: stop_vserver_response

    - name: Save operation details to file
      copy:
        content: |
          stop_cifs_response: {{ stop_cifs_response | to_nice_yaml }}
          volumes_response: {{ volumes_response | to_nice_yaml }}
          snapshot_responses: {{ snapshot_responses | to_nice_yaml }}
          stop_vserver_response: {{ stop_vserver_response | to_nice_yaml }}
        dest: manage_source_vserver_details.yml
